# Generated by Django 2.1.7 on 2019-03-10 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokhara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nepal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.FloatField()),
                ('district', models.CharField(max_length=50)),
                ('gapa_napa', models.CharField(max_length=50)),
                ('type_gn', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
